name: CI - Linter & Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Install, Lint & Test
    runs-on: ubuntu-latest
    outputs:
      cache-path: ${{ steps.cache-deps.outputs.cache-hit }}

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Cache de dependencias para evitar reinstalaciones innecesarias
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-cache

      # Paso 3: Instalar dependencias (solo si no existe cache)
      - name: Install dependencies
        run: npm install
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - run: npm run lint
      - run: npm test
