name: CI - Linter & Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-path: ${{ steps.cache-deps.outputs.cache-hit }}

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Cache de dependencias para evitar reinstalaciones innecesarias
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-cache

      # Paso 3: Instalar dependencias (solo si no existe cache)
      - name: Install dependencies
        run: npm install
        if: steps.cache-deps.outputs.cache-hit != 'true'

  # Trabajo de Linter
  linter:
    name: Run Linter
    runs-on: ubuntu-latest
    needs: setup # Dependencia del job de setup para no duplicar pasos

    steps:
      # Paso 4: Correr el linter
      - name: Run ESLint
        run: |
          ls -la
          cd ..
          ls -la
          cd ..
          npm run lint

  # Trabajo de Tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [setup, linter] # Dependencias del setup y el linter

    steps:
      # Paso 4: Correr los tests (después de linter)
      - name: Run Tests
        run: npm test
