name: CI - Linter & Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-path: ${{ steps.cache-deps.outputs.cache-hit }}

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso opcional: Ver la estructura del directorio después de clonar el repositorio
      - name: List files in root directory
        run: ls -la

      # Paso opcional: Ver la estructura de directorios dentro de una carpeta específica (si es necesario)
      - name: List files in Algorithms-and-Data-Structures directory
        run: |
          cd Algorithms-and-Data-Structures
          ls -la

      # Paso 2: Cache de dependencias
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache
          restore-keys: |
            ${{ runner.os }}-npm-cache

      # Paso 3: Instalar dependencias (solo si no existe cache)
      - name: Install dependencies
        run: |
          cd Algorithms-and-Data-Structures
          npm install
        if: steps.cache-deps.outputs.cache-hit != 'true'
